linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  gofumpt:
    lang-version: "1.21"
    extra-rules: true
  gci:
    sections:
      - standard
      - prefix(github.com/SixtyAI)
      - default
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: true

linters:
  enable-all: true
  disable:
  - maligned # Deprecated, see govet's fieldalignment instead.
  - exhaustivestruct # Deprecated.  Owner disappeared.  See exhaustruct.
  - golint # Deprecated.  Archived by owner.  See revive.
  - scopelint # Deprecated.  Archived by owner.  See exportloopref.
  - interfacer # Deprecated.  Archived by owner.
  - varcheck # Deprecated.  See unused.
  - ifshort # Deprecated.
  - deadcode # Deprecated.  See unused.
  - nosnakecase # Deprecated.  See revive(var-naming).
  - structcheck # Deprecated.
  # The following are turned off because I'm not sure they're helpful:
  - exhaustruct
  - forbidigo
  # Turning this off because it's in conflict with gofmt:
  - nolintlint
  # Turning this off because we're not ready for that level of overhead.
  - depguard # See: https://github.com/OpenPeeDeeP/depguard

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
